theme: jekyll-theme-slate
layout: page
title: Mondaydarknight
author: MongChe Lee
email: mondaydarknight@gmail.com
url: https://mondaydarknight.github.io
paginate: 5
plugins:
  - jekyll-paginate
github_url: https://github.com/mondaydarknight
twitter_url: https://twitter.com/mondaydarknight
